CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Games" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "GameHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GameId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "BorrowDate" date NOT NULL,
    "ReturnDate" date,
    "State" text NOT NULL DEFAULT 'Free',
    CONSTRAINT "PK_GameHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GameHistories_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GameHistories_GameId" ON "GameHistories" ("GameId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240519092520_InitialCreate', '8.0.5');

COMMIT;

